### ISSUE TITLE
Linux build with byacc fails, works with bison

### ISSUE THREAD

**Issue by mthuurne** [rednex/rgbds#333] opened 2019-04-20 16:44 UTC
The README suggests installing byacc, but when I try to build with byacc, this is the result:
```
$ make YACC=byacc
byacc: 1 shift/reduce conflict, 3 reduce/reduce conflicts.
src/asm/asmy.c:480:23: error: conflicting types for ‘yylex’
 # define YYLEX_DECL() yylex(void)
                       ^
src/asm/asmy.c:485:5: note: in expansion of macro ‘YYLEX_DECL’
 int YYLEX_DECL();
     ^~~~~~~~~~
In file included from include/asm/fstack.h:20:0,
                 from src/asm/asmy.y:21:
include/asm/lexer.h:66:10: note: previous declaration of ‘yylex’ was here
 uint32_t yylex(void);
          ^~~~~
make: *** [Makefile:121: src/asm/asmy.o] Error 1
```
However, if I install bison and build with that, the build succeeds: (still with warnings though)
```
$ make
src/asm/asmy.y: warning: 1 shift/reduce conflict [-Wconflicts-sr]
src/asm/asmy.y: warning: 3 reduce/reduce conflicts [-Wconflicts-rr]
```
I'm using the current master branch (a37a09c0) on openSUSE Leap 15.0.

**Comment by AntonioND** [comment] 2019-06-07 09:35
Can you try again? This patch should have fixed it: https://github.com/rednex/rgbds/commit/40006c6152935c420b2ad2ecf1ccdfde355fa215

**Comment by AntonioND** [comment] 2019-07-07 10:50
Have you tried with the latest master since you had this problem?

**Comment by AntonioND** [comment] 2019-07-11 23:52
This is the same problem as https://github.com/rednex/rgbds/issues/331. Considering that that issue has been fixed, I guess this has also been fixed. I'm closing the issue, but it can be reopen if the problem is still there.

**Closed by AntonioND** 2019-07-11 23:52 UTC
