### ISSUE TITLE
Impossible character escapes in strings

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#290] opened 2018-06-12 17:06 UTC
I have a simple macro:
```
dstr: MACRO
    REPT _NARG
        db \1
        shift
    ENDR
    db 0
ENDM
```

And I pass it this string:
```
    dstr "Line 1\nLine 2"
```
And I get this error:
```
ERROR: engine.asm(7) -> engine/title.asm(1357) -> dstr(3) -> dstr(1):
    Unterminated string
```

I then try to pass this string instead:
```
    dstr "Line1\\\nLine2"
```
And I get this error:
```
ERROR: engine.asm(7) -> engine/title.asm(1357) -> dstr(3) -> dstr(1):
    Illegal character escape '
'
```

I would expect either of these variants to work, since they're [right there in the manual](https://rednex.github.io/rgbds/rgbasm.5.html#String_Expressions)!

**Comment by ISSOtm** [comment] 2018-06-12 17:39
Well, I figured out that the correct answer was `\\n`. Which both isn't intuitive and not really pointed to in the manual. Plus the `Unterminated string` error doesn't give much insight as to what to do - I only knew what to do because I had encountered it using commas.

**Comment by AntonioND** [comment] 2018-06-12 20:57
Well, it makes sense. The `\\` is converted to `\` after the first pass. If you do the same to the `n`, `\n` will be converted to a newline.

Where is the problem in the manual?

I agree that the error messages aren't always helpful, but it's quite hard to get the parser to say useful things in some cases...

**Comment by ISSOtm** [comment] 2018-06-12 21:51
Well, the manual states that [`\,` is an escape sequence](https://rednex.github.io/rgbds/rgbasm.5.html#\,), so when I got an `Unterminated string` error after using a comma, I thought of escaping it. But I expected [`\n`](https://rednex.github.io/rgbds/rgbasm.5.html#\n) to work as well, which it didn't.

In retrospect, `\\n` does make sense, but it's not obvious to have the idea -- it took me a day to have that idea.

**Comment by ISSOtm** [comment] 2018-06-12 23:08
That's also my guess, although the parser actually attempts to escape the line feed, instead of calling it an unterminated string. But that's just nitpicking.

**Comment by AntonioND** [comment] 2018-06-12 23:30
However, even though this is not a bug, maybe the documentation can be updated. The documentation has an example, actually:
```
Line continuations work as usual inside macros or lists of arguments of macros.
Strings, however, are a bit trickier. The following example shows how to use
strings as arguments for a macro:

    PrintMacro : MACRO 
        PRINTT \1 
    ENDM 
 
        PrintMacro STRCAT(\"Hello\"\,  \ 
                          \" world\\n\")
```    
Maybe it's just in the wrong place.

**Comment by ISSOtm** [comment] 2018-06-13 09:47
I think it is. It also feels weird to have to escape everything, because there are no quotes wrapping the argument. Intuitively, it feels like you shouldn't have to escape those...

**Comment by AntonioND** [comment] 2018-06-13 23:14
Well, that's a macro argument, and macro arguments are a tricky thing...

The problem is that the parser isn't great and there are many hacks everywhere. This is a problem that isn't going to go away.

The only thing I can do is to change the docs, but I don't know where to put that, so I'm open for suggestions.

**Comment by AntonioND** [comment] 2018-06-13 23:14
RE: They are tricky things: https://github.com/rednex/rgbds/issues/63

**Comment by AntonioND** [comment] 2018-07-01 19:51
I'm going to close this. If you have a suggestion on how to change the docs feel free to propose it.

**Closed by AntonioND** 2018-07-01 19:51 UTC
Labels: docs, enhancement, rgbasm
