### ISSUE TITLE
rgbgfx crash in create_tilemap()

### ISSUE THREAD

**Issue by bentley** [rednex/rgbds#252] opened 2018-03-11 22:22 UTC
Two of the projects in run-tests.sh do not build on OpenBSD, because rgbgfx crashes.

https://github.com/pret/pokered.git:

    rgbgfx -d1  -o gfx/minimized_mon_sprite.1bpp gfx/minimized_mon_sprite.png
    gmake: *** [Makefile:74: gfx/minimized_mon_sprite.1bpp] Segmentation fault (core dumped)

https://github.com/pret/pokecrystal.git:

    rgbgfx  -o gfx/mobile/up_arrow.2bpp gfx/mobile/up_arrow.png
    gmake: *** [Makefile:232: gfx/mobile/up_arrow.2bpp] Segmentation fault (core dumped)

The backtrace is the same in both crashes:

    #0  0x00001c3c97c00e2d in create_tilemap (opts=0x7f7fffffa2e0, 
        gb=0x7f7fffffa298, tilemap=0x7f7fffffa288) at src/gfx/gb.c:127
    #1  0x00001c3c97c01b80 in main (argc=1, argv=0x7f7fffffa3b0)
        at src/gfx/main.c:230

**Comment by AntonioND** [comment] 2018-03-12 00:31
The sprites are 8x4 sprites, so I guess the problem is related to https://github.com/rednex/rgbds/pull/235/commits/8fe52930776f8803c215c67e22ba558db5e360bb. It's weird that this doesn't happen in Linux, though .Maybe caused some small difference in the memory handling of libpng?

**Comment by AntonioND** [comment] 2018-03-15 21:18
By the way, which version of libpng do you have, @bentley?

**Comment by Sanqui** [comment] 2018-03-15 21:47
cc @obskyr

**Comment by obskyr** [comment] 2018-03-15 22:27
8fe52930 itself doesn't have to do with this, as before 30759453 there was no input validation at all on width and height.

However, I do believe you're on the right track - the height may very well be the culprit in this case. I haven't taken more than a cursory glance at that code, but... if that line 127 is the current line 127, it looks like not enough memory is allocated for the tilemap's pointers to the tiles. That could, for example, be due to the `GBImage`'s size being set too low for some reason. I doubt it has to do with libpng, as the PNG's already gone through two data transformations without problem at that point (PNG -> `RawIndexedImage` -> `GBImage`), but there could of course be something I'm missing.

I'd have to dig deeper in the tilemap code to be more certain. One important question, though, is... why the heck does rgbgfx call `create_tilemap` when you're not even making a tile map (and `opts.unique` isn't set, which `create_tilemap` seems to handle)? 😅

**Comment by AntonioND** [comment] 2018-03-20 20:30
Fixed in https://github.com/rednex/rgbds/pull/258.

**Closed by AntonioND** 2018-03-20 20:30 UTC
