### ISSUE TITLE
[FEATURE REQUEST] Date/time numeric constants

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#170] opened 2017-04-13 18:08 UTC
I just found myself writing very odd macros just to extract the date of compilation:

```
ST_DAY   = (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 10, 1) - $30) * 10 + (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 11, 1) - $30) + (-1)
ST_MONTH = (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 7, 1) - $30) * 10 + (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 8, 1) - $30) + (-1)
ST_YEAR  = (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 4, 1) - $30) * 10 + (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 5, 1) - $30)
ST_YEAR  = ST_YEAR + (STRSUB({__TIMESTAMP_ISO_8601_UTC__}, 3, 1) - $30) * 100
```

Wouldn't it be much simpler to be able to do something like this?

```
ST_DAY   = __UTC_DAY__ - 1
ST_MONTH = __UTC_MONTH__ - 1
ST_YEAR  = __UTC_YEAR__ - 2000
```

**Comment by AntonioND** [comment] 2017-04-13 18:47
I didn't create these symbols to be used like that, I expected people to use the whole string. xD But yeah, adding what you suggest is quite reasonable. I'd even add hours, minutes and seconds.

**Comment by bentley** [comment] 2017-04-14 00:58
Personally I’m not a fan of anything that introduces nondeterminism into a build. Makes more sense to insert a version control revision ID instead, and that’s outside the scope of a toolchain. Just saying.

**Comment by aaaaaa123456789** [comment] 2017-04-14 01:00
That's a matter of policy for every ROM, now isn't it? It doesn't seem like
a good idea to force a style from the toolchain.

**Comment by bentley** [comment] 2017-04-14 01:03
It’s not “forcing a style” to say that kind of feature is out of scope for a toolchain, or just a bad idea.

Also, I’m just commenting. I have no control over what goes into RGBDS.

**Comment by aaaaaa123456789** [comment] 2017-04-14 01:06
What we're using this for can't be replaced by version numbers — we use the
build date as the default date when setting the internal calendar.

That being said, most build toolchains have a way of inserting timestamps,
so it doesn't seem out of scope to me.

**Comment by bentley** [comment] 2017-04-14 01:08
[And people who deal with other people’s build systems are starting to realize it’s not such a great feature.](https://reproducible-builds.org/docs/timestamps/)

That said, I’ve already derailed this bug report enough. I’ll stop talking about off‐topic stuff now.

**Comment by AntonioND** [comment] 2017-04-14 14:15
I see your point, @bentley. The problem is that, as this issue has made clear, there are people already using the old predefined symbols. Instead of forcing them to use hacks such as the one in the first post, I think it's better to just give them this. Actually, my reason for adding the ISO 8601 strings was that the assembler had the `__TIME__` and `__DATE__` symbols, but they were quite problematic because of not following any standard.

**Comment by AntonioND** [comment] 2017-04-22 10:18
Fixed  here: https://github.com/rednex/rgbds/pull/171

**Closed by AntonioND** 2017-04-22 10:18 UTC
