### ISSUE TITLE
Allow to specify working address of a section

### ISSUE THREAD

**Issue by AntonioND** [rednex/rgbds#272] opened 2018-04-30 21:35 UTC
I've just seen this tool by @zzazzdzz: https://github.com/zzazzdzz/rgbbin

Basicaly, it's a tool that lets the user write code in RAM sections (which is somehow loaded by another tool).

It is an interesting idea, and the GNU linker allows you to do it:
```
   It is possible to specify that a segment should be loaded at a
particular address in memory.  This is done using an `AT' expression.
This is identical to the `AT' command used in the `SECTIONS' command
(Section Options:.).  Using the `AT' command for a program   
header overrides any information in the `SECTIONS' command.
```

In short, you write some code in a ROM section, but specify that it is actually going to run at some address in RAM.

This is not a trivial change, but pretty much every single GB ROM does this when they copy the OAM update function to HRAM.

**Comment by ISSOtm** [comment] 2019-10-09 13:35
Closing this as a duplicate of #274

**Closed by ISSOtm** 2019-10-09 13:35 UTC
Labels: enhancement, rgbasm, rgblink
