### ISSUE TITLE
Problem compile failing

### ISSUE THREAD

**Issue by yuyat-sushi** [rednex/rgbds#367] opened 2019-06-29 08:47 UTC
一部ファイルにおいて、コンパイラがソースコードに対してコンパイルを行わず、ヘッダーを除いて何もない.outファイルを出力してしまう問題が発生しています。
コンパイルに成功するファイルとコンパイルに失敗するファイルを添付しましたので、原因の究明をお願いします。
For some files, the compiler does not compile the source code, and there is a problem that outputs an empty .out file except for the header.
We have attached a file that compiles successfully and a file that fails to compile, so please investigate the cause.
[Problematic project.zip](https://github.com/rednex/rgbds/files/3341676/Problematic.project.zip)

**Comment by dbrotz** [comment] 2019-06-29 18:45
The problem is that your source code file begins with a UTF-8 byte order mark (`0xEF,0xBB,0xBF`). It seems that rgbasm chokes when it encounters that. A workaround would be to simply remove the byte order mark, but this should be fixed.

**Comment by AntonioND** [comment] 2019-07-11 23:50
Pull request #359 has been merged. Is this problem fixed?

**Comment by ISSOtm** [comment] 2019-08-27 19:32
Using latest master, both projects included in the zip compiled fine (after I uncommented the `INCLUDE "hardware.inc"` in `Failed Project`, at least). This can probably be closed.

**Comment by AntonioND** [comment] 2019-08-28 00:29
This can be reopened if the issue persists.

**Closed by AntonioND** 2019-08-28 00:29 UTC
